# Generated by Django 2.1.3 on 2019-06-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190615_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can create/update/delete posts on the blog', 'Create or Update the posts'),)},
        ),
    ]
