# Generated by Django 2.1.3 on 2018-11-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181113_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(default='img_post/no-img.jpg', upload_to='img_post/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(related_name='images', to='blog.Image_Post'),
        ),
    ]
