# Generated by Django 2.1.3 on 2019-06-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190616_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post_on_blog', 'Create or Update the posts'),)},
        ),
    ]
