# Generated by Django 2.1.3 on 2019-02-12 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('character', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=200)),
                ('job', models.CharField(default='crew', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('imdb_id', models.CharField(default='', max_length=200)),
                ('tmdb_id', models.CharField(default='', max_length=200)),
                ('overview', models.TextField(default='')),
                ('release_date', models.DateField(null=True)),
                ('runtime', models.IntegerField(default=0)),
                ('tagline', models.TextField(default='')),
                ('backdrop_path', models.CharField(default='', max_length=200)),
                ('poster_path', models.CharField(default='', max_length=200)),
                ('original_language', models.CharField(default='', max_length=200)),
                ('original_title', models.CharField(default='', max_length=250)),
                ('country', models.ManyToManyField(blank=True, related_name='country', to='bifffidus.Country')),
                ('genre', models.ManyToManyField(blank=True, related_name='genre', to='bifffidus.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('tmdb_id', models.IntegerField(default=0)),
                ('profile_path', models.CharField(default='', max_length=200)),
                ('gender', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_movie', models.BooleanField(default=True)),
                ('festival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival', to='bifffidus.Festival')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_screening', to='bifffidus.Movie')),
                ('screen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen', to='bifffidus.Screen')),
            ],
        ),
        migrations.CreateModel(
            name='Spoken_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Movie_Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival_tag', to='bifffidus.Festival')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_tag', to='bifffidus.Movie')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='bifffidus.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='screen',
            field=models.ManyToManyField(blank=True, related_name='screen_place', to='bifffidus.Screen'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_company',
            field=models.ManyToManyField(blank=True, related_name='production_company', to='bifffidus.Production_Company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_language',
            field=models.ManyToManyField(blank=True, related_name='spoken_language', to='bifffidus.Spoken_Language'),
        ),
        migrations.AddField(
            model_name='festival',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='place', to='bifffidus.Place'),
        ),
        migrations.AddField(
            model_name='crew',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_crew', to='bifffidus.Movie'),
        ),
        migrations.AddField(
            model_name='crew',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_person', to='bifffidus.Person'),
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast', to='bifffidus.Movie'),
        ),
        migrations.AddField(
            model_name='cast',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_person', to='bifffidus.Person'),
        ),
    ]
