# Generated by Django 2.1.3 on 2018-11-28 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imdb_link', models.CharField(max_length=200)),
                ('overview', models.TextField(default='')),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('runtime', models.IntegerField(default=0)),
                ('tagline', models.TextField(default='')),
                ('backdrop_path', models.CharField(default='', max_length=200)),
                ('poster_path', models.CharField(default='', max_length=200)),
                ('original_language', models.CharField(default='', max_length=200)),
                ('original_title', models.CharField(default=models.CharField(max_length=200), max_length=200)),
                ('country', models.ManyToManyField(blank=True, related_name='country', to='bifffidus.Country')),
                ('credit', models.ManyToManyField(blank=True, related_name='credit', to='bifffidus.Credit')),
                ('genre', models.ManyToManyField(blank=True, related_name='genre', to='bifffidus.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('place', models.ManyToManyField(blank=True, related_name='place', to='bifffidus.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('festival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festival', to='bifffidus.Festival')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='bifffidus.Movie')),
                ('screen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen', to='bifffidus.Screen')),
            ],
        ),
        migrations.CreateModel(
            name='Spoken_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='production_company',
            field=models.ManyToManyField(blank=True, related_name='production_company', to='bifffidus.Production_Company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_language',
            field=models.ManyToManyField(blank=True, related_name='spoken_language', to='bifffidus.Spoken_Language'),
        ),
        migrations.AddField(
            model_name='credit',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='job', to='bifffidus.Job'),
        ),
        migrations.AddField(
            model_name='credit',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='person', to='bifffidus.Person'),
        ),
    ]
