# Generated by Django 2.1.3 on 2018-11-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0002_auto_20181129_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
