# Generated by Django 2.1.3 on 2018-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0003_auto_20181129_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='festival',
        ),
        migrations.AddField(
            model_name='movie',
            name='festival',
            field=models.ManyToManyField(blank=True, related_name='festival', to='bifffidus.Festival'),
        ),
    ]
