# Generated by Django 2.1.3 on 2019-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0003_auto_20190218_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='cast', to='bifffidus.Cast'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='crew', to='bifffidus.Crew'),
        ),
    ]
