# Generated by Django 2.1.3 on 2019-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0004_auto_20190221_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movie_cast', to='bifffidus.Cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='movie_crew', to='bifffidus.Crew'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='movie_genre', to='bifffidus.Genre'),
        ),
    ]
