# Generated by Django 2.1.3 on 2019-02-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0005_auto_20190222_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagtype',
            field=models.CharField(default='Other', max_length=200),
        ),
    ]
