# Generated by Django 2.1.3 on 2019-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0006_tag_tagtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagtype',
            field=models.CharField(default='other', max_length=200),
        ),
    ]
