# Generated by Django 2.1.3 on 2018-12-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0006_auto_20181201_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='festival',
        ),
        migrations.AddField(
            model_name='screening',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festival', to='bifffidus.Festival'),
        ),
    ]
