# Generated by Django 2.1.3 on 2019-01-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0007_auto_20181201_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='place',
        ),
        migrations.AddField(
            model_name='festival',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place', to='bifffidus.Place'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
