# Generated by Django 2.1.3 on 2019-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0008_auto_20190115_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='screen',
            field=models.ManyToManyField(blank=True, related_name='screen_place', to='bifffidus.Screen'),
        ),
    ]
