# Generated by Django 2.1.3 on 2019-02-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0008_tag_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='img',
            new_name='img_path',
        ),
    ]
