# Generated by Django 2.1.3 on 2019-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0009_place_screen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='room',
            new_name='room_name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
