# Generated by Django 2.1.3 on 2019-02-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0009_auto_20190223_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='img_path',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
