# Generated by Django 2.1.3 on 2019-02-04 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0010_auto_20190131_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='screening',
            name='is_movie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_type', to='bifffidus.Tag_Type'),
        ),
        migrations.AddField(
            model_name='screening',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='bifffidus.Tag'),
        ),
    ]
