# Generated by Django 2.1.3 on 2019-02-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0011_remove_tag_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagtype',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_type', to='bifffidus.Tag_Type'),
        ),
    ]
