# Generated by Django 2.1.3 on 2019-02-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0012_auto_20190204_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival', to='bifffidus.Festival'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='bifffidus.Movie'),
        ),
    ]
