# Generated by Django 2.1.3 on 2019-03-01 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0013_festival_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_movie_festival',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='tag_movie_festival',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tag_movie_festival',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='is_movie',
        ),
        migrations.AddField(
            model_name='screening',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screening_tag', to='bifffidus.Tag'),
        ),
        migrations.DeleteModel(
            name='Tag_Movie_Festival',
        ),
    ]
