# Generated by Django 2.1.3 on 2019-02-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0013_auto_20190204_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen', to='bifffidus.Screen'),
        ),
        migrations.AlterField(
            model_name='tag_movie_festival',
            name='festival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival_tag', to='bifffidus.Festival'),
        ),
        migrations.AlterField(
            model_name='tag_movie_festival',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_tag', to='bifffidus.Movie'),
        ),
        migrations.AlterField(
            model_name='tag_movie_festival',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='bifffidus.Tag'),
        ),
    ]
