# Generated by Django 2.1.3 on 2019-03-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0014_auto_20190301_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='tag',
        ),
        migrations.AddField(
            model_name='screening',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='screening_tag', to='bifffidus.Tag'),
        ),
    ]
