# Generated by Django 2.1.3 on 2019-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0015_auto_20190301_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
