# Generated by Django 2.1.3 on 2019-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0016_tag_icon_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
