# Generated by Django 2.1.3 on 2019-03-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0017_auto_20190301_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
