# Generated by Django 2.1.3 on 2019-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0020_auto_20190304_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='poster_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
