# Generated by Django 2.1.3 on 2019-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0021_auto_20190304_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
