# Generated by Django 2.1.3 on 2019-03-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0022_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
