# Generated by Django 2.1.3 on 2019-03-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0023_remove_tag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_job', to='bifffidus.Department'),
        ),
    ]
