# Generated by Django 2.1.3 on 2019-03-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0024_auto_20190314_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
