# Generated by Django 2.1.3 on 2019-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0025_auto_20190315_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_pertinent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
