# Generated by Django 2.1.3 on 2019-03-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifffidus', '0027_auto_20190319_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='character',
            field=models.CharField(default='', max_length=350),
        ),
    ]
