# Generated by Django 2.1.3 on 2019-06-15 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio_file', models.FileField(upload_to='media/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_file', models.ImageField(upload_to='media/img/')),
            ],
        ),
    ]
