# Generated by Django 2.1.3 on 2019-06-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azaplayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_post',
            name='uploaded_date',
        ),
    ]
