# Generated by Django 2.1.3 on 2019-06-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azaplayer', '0003_auto_20190616_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_post',
            name='audiofile',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='image_post',
            name='image_file',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
